--- #YAML:1.0
name:               DBIx-Simple-OO
version:            0.02
abstract:           Retrieve database rows as objects
author:
    - Jos Boumans <kane[at]cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBIx::Simple:      0
    Object::Accessor:  0
    Test::More:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
