# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-Simple-OO
version:      0.01
version_from: lib/DBIx/Simple/OO.pm
installdirs:  site
requires:
    DBIx::Simple:                  0
    Object::Accessor:              0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.25
