---
abstract: 'Retrieve database rows as objects'
author:
  - 'Jos Boumans <kane[at]cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.74, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Simple-OO
no_index:
  directory:
    - t
    - inc
requires:
  DBI: 1.624
  DBIx::Simple: 0
  Object::Accessor: 0
  Test::More: 0
resources:
  repository: git://github.com/jib/dbix-simple-oo.git
version: 0.02
